import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar is auto-generated from the docs/ directory.
// Chapter order comes from sidebar_position in each chapter's front matter.
// Category names/order come from _category_.json in each subdirectory.

const sidebars: SidebarsConfig = {
  bookSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
